# docker network create mynetwork
# docker run -d --name web1 --net mynetwork jmalloc/echo-server
services:
  web:
    image: jmalloc/echo-server
    
# 같은 이미지이므로 3번 기동


# docker run -d --name haproxy --net mynetwork \
# -v $(pwd):/usr/local/etc/haproxy:ro \
# -p 80:80 -p 8404:8404 \haproxytech/haproxy-alpine:2.7
  haproxy:
    image: haproxytech/haproxy-alpine:2.7     
    volumes:
      - "./config:/usr/local/etc/haproxy:ro"
    ports:
      - "80:80"
    depends_on:
      - web 
      
# 바인드 마운트 방식이므로 볼륨 정의 안됨. 임의 위치임

